
"""
Capability-claim guardrail for NexaTune AI.

Purpose
-------
Detect unsupported capability claims generated by the model, such as:

- connecting a customer to a human agent
- transferring a conversation
- initiating or processing a refund
- cancelling an order or subscription
- modifying account/order information
- claiming that a backend action has already been completed
- making unsupported guarantees about actions

The guardrail provides:

1. SYSTEM_PROMPT_ADDENDUM
   Prompt-level instructions to reduce unsupported claims.

2. scan_for_unsupported_claims()
   Lightweight regex-based post-generation detection.

3. get_safe_response()
   Context-aware remediation response.

This is a lightweight first-line guardrail and does not replace
application authorization, backend validation, logging, monitoring,
or production security controls.
"""

import re
from dataclasses import dataclass, field


# ============================================================
# PROMPT-LEVEL GUARDRAIL
# ============================================================

SYSTEM_PROMPT_ADDENDUM = (
    "You are a customer-support assistant with informational capabilities "
    "only. You cannot connect the user to a human agent, transfer the chat, "
    "place or cancel orders, issue or initiate refunds, modify account or "
    "order information, or confirm that any backend action has already "
    "been taken. If the user requests one of these actions, do not imply "
    "that you are performing it. Clearly explain the limitation and "
    "provide appropriate guidance for contacting the relevant support "
    "channel."
)


# ============================================================
# CLAIM CATEGORIES
# ============================================================

HUMAN_HANDOFF = "human_handoff"
REFUND_ACTION = "refund_action"
ORDER_CANCELLATION = "order_cancellation"
BACKEND_ACTION = "backend_action"
UNSUPPORTED_COMMITMENT = "unsupported_commitment"


# ============================================================
# UNSUPPORTED CLAIM PATTERNS
# ============================================================

UNSUPPORTED_CLAIM_PATTERNS = {

    # --------------------------------------------------------
    # Human handoff / live transfer
    # --------------------------------------------------------

    HUMAN_HANDOFF: [
        r"\bconnect(?:ing)? you (?:with|to) (?:one of )?our\b",
        r"\ballow me a moment to connect\b",
        r"\btransferring you\b",
        r"\btransfer you\b",
        r"\bplease hold while I\b",
        r"\bconnect you to (?:a |our )?(?:human|agent|representative|support)\b",
        r"\bconnect you with (?:a |our )?(?:human|agent|representative|support)\b",
        r"\bput you through to (?:a |our )?(?:human|agent|representative|support)\b",
        r"\btransfer(?:ring)? (?:this|the) conversation\b",
        r"\bget you connected to (?:a |our )?(?:human|agent|representative|support)\b",
    ],

    # --------------------------------------------------------
    # Refund / payment actions
    # --------------------------------------------------------

        REFUND_ACTION: [
        r"\bI('ll| will) (?:initiate|process|issue|expedite|complete|handle|start) "
        r"(?:the |a )?refund\b",

        r"\bI can (?:initiate|process|issue|expedite|complete|handle|start) "
        r"(?:the |a )?refund\b",

        r"\bI('ll| will) (?:process|handle|complete|issue) "
        r"(?:the |your )?(?:payment|refund)\b",

        r"\b(?:initiate|process|issue|expedite|complete|handle|start) "
        r"(?:the |a |your )?refund (?:for you|on your behalf)\b",

        r"\bI('ve| have) (?:processed|issued|refunded|completed) "
        r"(?:the |your )?(?:refund|payment)\b",

        r"\byour refund has been "
        r"(?:processed|issued|completed|initiated)\b",

        r"\brefund (?:has been|was) "
        r"(?:processed|issued|completed|initiated)\b",

        r"\bI('ll| will) take care of "
        r"(?:the |your )?refund\b",

        r"\bI('ll| will) do everything I can\b.*\brefund\b",

        # Indirect refund-action claims
        r"\b(?:help|allow|enable) me\b.*\b(?:initiate|process|issue|complete|handle)\b.*\brefund\b",

        r"\bI('ll| will| can)\b.*\b(?:initiate|process|issue|complete|handle)\b.*\brefund\b",

        r"\bI\b.*\b(?:locate|find|access)\b.*\border\b.*\b(?:initiate|process|issue)\b.*\brefund\b",
    ],

    # --------------------------------------------------------
    # Order / subscription cancellation
    # --------------------------------------------------------

    ORDER_CANCELLATION: [
        r"\bI('ll| will) cancel "
        r"(?:the |your )?(?:order|subscription)\b",

        r"\bI can cancel "
        r"(?:the |your )?(?:order|subscription)\b",

        r"\bI('ve| have) cancelled "
        r"(?:the |your )?(?:order|subscription)\b",

        r"\bI('ve| have) canceled "
        r"(?:the |your )?(?:order|subscription)\b",

        r"\byour (?:order|subscription) has been "
        r"(?:cancelled|canceled)\b",

        r"\bI'll cancel it for you\b",

        r"\bI will cancel it for you\b",
    ],

    # --------------------------------------------------------
    # Backend action claims
    # --------------------------------------------------------

    BACKEND_ACTION: [
        r"\bI('ll| will) "
        r"(?:process|submit|update|change|modify|complete) "
        r"(?:the |your )?"
        r"(?:request|order|account|details|information)\b",

        r"\bI can "
        r"(?:process|submit|update|change|modify|complete) "
        r"(?:the |your )?"
        r"(?:request|order|account|details|information)\b",

        r"\bI('ve| have) "
        r"(?:processed|submitted|updated|changed|modified|completed) "
        r"(?:the |your )?"
        r"(?:request|order|account|details|information)\b",

        r"\byour (?:request|case|issue) has been "
        r"(?:submitted|processed|updated|completed)\b",

        r"\byour order has been "
        r"(?:updated|processed|completed)\b",

        r"\bthe change has been applied\b",

        r"\bthe change was applied\b",

        r"\bI've made the change\b",

        r"\bI have made the change\b",

        r"\bI've updated your account\b",

        r"\bI have updated your account\b",
    ],

    # --------------------------------------------------------
    # Unsupported commitments / guarantees
    #
    # IMPORTANT:
    # Keep this category focused on actual guarantees or
    # capability commitments.
    #
    # Generic phrases such as:
    #   "I'll make it happen"
    #   "I'll handle it"
    #   "I'll take care of it"
    #
    # are intentionally NOT blocked because they can appear
    # in otherwise informational customer-support responses.
    # --------------------------------------------------------

    UNSUPPORTED_COMMITMENT: [
        r"\bI guarantee\b",

        r"\bI can guarantee\b",

        r"\bI will guarantee\b",

        r"\bI'll guarantee\b",

        r"\brest assured,?\s+(?:I|we)'ve\b",

        r"\brest assured,?\s+I can\b",

        r"\brest assured,?\s+I will\b",

        r"\brest assured,?\s+I'll\b",

        r"\bI('ll| will) ensure\b.*\b(?:refund|payment|order|account)\b",

        r"\bI('ll| will) make sure\b.*\b(?:refund|payment|order|account)\b",
    ],
}


# ============================================================
# COMPILE PATTERNS
# ============================================================

_COMPILED_PATTERNS = {
    category: [
        re.compile(pattern, re.IGNORECASE)
        for pattern in patterns
    ]
    for category, patterns in UNSUPPORTED_CLAIM_PATTERNS.items()
}


# ============================================================
# RESULT OBJECT
# ============================================================

@dataclass
class GuardrailResult:
    flagged: bool
    matches: list[str] = field(default_factory=list)
    categories: list[str] = field(default_factory=list)

    def as_dict(self):
        return {
            "flagged": self.flagged,
            "matches": self.matches,
            "categories": self.categories,
        }


# ============================================================
# DETECTION
# ============================================================

def scan_for_unsupported_claims(
    response_text: str,
) -> GuardrailResult:
    """
    Scan generated model output for unsupported capability claims.

    Returns:
        GuardrailResult:
            flagged:
                True when an unsupported claim is detected.

            matches:
                Exact matched phrases.

            categories:
                Capability categories responsible for the detection.
    """

    # --------------------------------------------------------
    # Empty response
    # --------------------------------------------------------

    if not response_text or not response_text.strip():
        return GuardrailResult(
            flagged=False,
            matches=[],
            categories=[],
        )

    matches = []
    categories = []

    # --------------------------------------------------------
    # Scan every category
    # --------------------------------------------------------

    for category, patterns in _COMPILED_PATTERNS.items():

        category_flagged = False

        for pattern in patterns:

            match = pattern.search(response_text)

            if match is None:
                continue

            matched_text = match.group(0)

            # Avoid duplicate exact matches.
            if matched_text not in matches:
                matches.append(matched_text)

            # Add each category only once.
            if not category_flagged:
                categories.append(category)
                category_flagged = True

    return GuardrailResult(
        flagged=len(matches) > 0,
        matches=matches,
        categories=categories,
    )


# ============================================================
# SAFE RESPONSE GENERATION
# ============================================================

def get_safe_response(
    matches: list[str],
    categories: list[str] | None = None,
) -> str:
    """
    Generate a safe customer-facing response based on
    detected unsupported capability categories.

    Specific capability categories take priority over the
    generic unsupported-commitment category.
    """

    categories = categories or []

    # --------------------------------------------------------
    # Human handoff
    # --------------------------------------------------------

    if HUMAN_HANDOFF in categories:

        return (
            "I can help you with your customer support request, "
            "but I cannot directly connect you to a human representative "
            "or transfer this conversation. Please contact the appropriate "
            "customer support channel for human assistance."
        )

    # --------------------------------------------------------
    # Refund
    # --------------------------------------------------------

    if REFUND_ACTION in categories:

        return (
            "I can provide information about your refund request, "
            "but I cannot directly process, issue, or initiate refunds. "
            "Please use the appropriate customer support channel "
            "to complete or verify the refund request."
        )

    # --------------------------------------------------------
    # Cancellation
    # --------------------------------------------------------

    if ORDER_CANCELLATION in categories:

        return (
            "I can help explain the cancellation process, "
            "but I cannot directly cancel an order or subscription. "
            "Please use the appropriate customer support channel "
            "to complete the cancellation."
        )

    # --------------------------------------------------------
    # Backend action
    # --------------------------------------------------------

    if BACKEND_ACTION in categories:

        return (
            "I can help explain the relevant process, "
            "but I cannot directly make or confirm backend changes. "
            "Please use the appropriate customer support channel "
            "to verify or complete the request."
        )

    # --------------------------------------------------------
    # Unsupported commitment
    # --------------------------------------------------------

    if UNSUPPORTED_COMMITMENT in categories:

        return (
            "I can provide guidance based on the information available "
            "to me, but I cannot guarantee or directly perform actions "
            "in your account."
        )

    # --------------------------------------------------------
    # Generic fallback
    # --------------------------------------------------------

    return (
        "I can provide guidance based on the information available "
        "to me, but I cannot directly perform or confirm backend actions. "
        "Please use the appropriate customer support channel for assistance."
    )


# ============================================================
# LOCAL TESTS
# ============================================================

if __name__ == "__main__":

    test_cases = [

        # ----------------------------------------------------
        # Case 1: Human handoff
        # ----------------------------------------------------

        (
            "We're here to help! I take note that you need assistance "
            "in speaking to a person. Please allow me a moment to "
            "connect you with one of our representatives."
        ),

        # ----------------------------------------------------
        # Case 2: Human support connection
        # ----------------------------------------------------

        (
            "I'm here to help you with that. To connect you with "
            "our dedicated customer support team, please provide "
            "me with some additional information."
        ),

        # ----------------------------------------------------
        # Case 3: Refund initiation
        # ----------------------------------------------------

        (
            "Please provide your transaction ID and I will initiate "
            "the refund process for you."
        ),

        # ----------------------------------------------------
        # Case 4: Refund processing
        # ----------------------------------------------------

        (
            "Please provide your payment details so I can process "
            "the refund as quickly as possible."
        ),

        # ----------------------------------------------------
        # Case 5: Unsupported commitment
        # ----------------------------------------------------

        (
            "Rest assured, I'll do everything I can to expedite "
            "your refund and take care of it for you."
        ),

        # ----------------------------------------------------
        # Case 6: Already completed refund
        # ----------------------------------------------------

        (
            "I've processed your refund and updated your account."
        ),

        # ----------------------------------------------------
        # Case 7: Cancellation
        # ----------------------------------------------------

        (
            "I'll cancel your subscription right away."
        ),

        # ----------------------------------------------------
        # Case 8: Safe normal response
        # ----------------------------------------------------

        (
            "I'm sorry to hear that. Could you tell me more about "
            "the issue you're facing so I can point you to the "
            "right resource?"
        ),

        # ----------------------------------------------------
        # Case 9: Safe refund limitation
        # ----------------------------------------------------

        (
            "I cannot process refunds directly, but I can explain "
            "the refund process."
        ),

        # ----------------------------------------------------
        # Case 10: Safe human limitation
        # ----------------------------------------------------

        (
            "I cannot connect you to a human representative, "
            "but I can explain how to contact customer support."
        ),

        # ----------------------------------------------------
        # Case 11: Previous real failure mode
        # ----------------------------------------------------

        (
            "I'm sorry to hear that you need to refund your payment "
            "immediately. Please provide the details and I'll initiate "
            "the refund process as quickly as possible. Rest assured, "
            "I'll do everything I can to expedite your refund."
        ),

        # ----------------------------------------------------
        # Case 12: Backend update
        # ----------------------------------------------------

        (
            "I've updated your account and completed the request."
        ),

        # ----------------------------------------------------
        # Case 13: Regression test
        # Generic phrase should NOT trigger guardrail.
        # ----------------------------------------------------

        (
            "I'll make it happen! I completely understand your need "
            "to locate your invoice for your recent order. To find "
            "the invoice, log in to your account and navigate to "
            "the Orders or Billing section."
        ),

        # ----------------------------------------------------
        # Case 14: Another safe conversational phrase
        # ----------------------------------------------------

        (
            "I'll take care of explaining the steps for locating "
            "your invoice. You can find it in the Billing section."
        ),
    ]

    print("=" * 70)
    print("NexaTune Capability Guardrail Tests")
    print("=" * 70)

    flagged_count = 0
    safe_count = 0

    for i, text in enumerate(test_cases, 1):

        result = scan_for_unsupported_claims(text)

        print()
        print(f"Case {i}")
        print("-" * 70)

        print(f"Flagged    : {result.flagged}")
        print(f"Categories : {result.categories}")
        print(f"Matches    : {result.matches}")

        if result.flagged:

            flagged_count += 1

            print("Safe response:")

            print(
                get_safe_response(
                    result.matches,
                    result.categories,
                )
            )

        else:

            safe_count += 1

            print(
                "Result     : "
                "No unsupported capability claim detected."
            )

    print()
    print("=" * 70)
    print("Guardrail Test Summary")
    print("=" * 70)

    print(f"Total cases : {len(test_cases)}")
    print(f"Flagged     : {flagged_count}")
    print(f"Safe        : {safe_count}")

    print("=" * 70)
